import React from 'react';
import { Activity, Cpu, ExternalLink } from 'lucide-react';

export default function GrafanaView({ pipelineData }) {
  return (
    <div className="glass-card" style={{ padding: '32px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ fontSize: '1.2rem', fontWeight: 700, color: '#fff', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Activity size={20} color="var(--accent-emerald)" /> Grafana AI Observability & MCP Telemetry
          </h2>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginTop: '2px' }}>
            Real-time OTLP Metrics, Prometheus Counters, and Model Latency Traces
          </p>
        </div>

        <a 
          href="https://quirkyviper1507.grafana.net" 
          target="_blank" 
          rel="noreferrer" 
          className="btn-chip"
          style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '6px' }}
        >
          Open Grafana Cloud Stack <ExternalLink size={13} />
        </a>
      </div>

      {/* Metric Cards Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px' }}>
        <div style={{ background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.25)', padding: '20px', borderRadius: '16px' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--accent-emerald)', textTransform: 'uppercase', fontFamily: 'var(--font-mono)' }}>
            Pipeline Duration
          </span>
          <h3 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#fff', marginTop: '4px' }}>
            {pipelineData ? `${pipelineData.pipeline_duration_seconds}s` : '0.0s'}
          </h3>
          <p style={{ fontSize: '0.72rem', color: 'var(--text-tertiary)', marginTop: '2px' }}>Multi-Agent Latency</p>
        </div>

        <div style={{ background: 'rgba(0, 242, 254, 0.08)', border: '1px solid rgba(0, 242, 254, 0.25)', padding: '20px', borderRadius: '16px' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--accent-cyan)', textTransform: 'uppercase', fontFamily: 'var(--font-mono)' }}>
            Active Sub-Agents
          </span>
          <h3 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#fff', marginTop: '4px' }}>3 Agents</h3>
          <p style={{ fontSize: '0.72rem', color: 'var(--text-tertiary)', marginTop: '2px' }}>Script, Visual, Audio Agents</p>
        </div>

        <div style={{ background: 'rgba(123, 44, 191, 0.08)', border: '1px solid rgba(123, 44, 191, 0.25)', padding: '20px', borderRadius: '16px' }}>
          <span style={{ fontSize: '0.72rem', color: 'var(--accent-purple)', textTransform: 'uppercase', fontFamily: 'var(--font-mono)' }}>
            Prometheus Stream
          </span>
          <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#fff', marginTop: '8px', fontFamily: 'var(--font-mono)' }}>
            /metrics
          </h3>
          <p style={{ fontSize: '0.72rem', color: 'var(--text-tertiary)', marginTop: '2px' }}>Grafana OTLP Endpoint Active</p>
        </div>
      </div>

      {/* Telemetry Output Stream */}
      <div style={{ background: 'rgba(8, 9, 13, 0.8)', border: '1px solid var(--border-subtle)', borderRadius: '16px', padding: '20px' }}>
        <h4 style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '12px', fontFamily: 'var(--font-mono)', display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Cpu size={14} /> Live Prometheus Stream Output:
        </h4>
        <pre style={{ fontFamily: 'var(--font-mono)', fontSize: '0.78rem', color: 'var(--accent-cyan)', overflowX: 'auto', background: '#040508', padding: '16px', borderRadius: '12px', border: '1px solid rgba(255, 255, 255, 0.05)', lineHeight: '1.6' }}>
{`# HELP agent_task_executions_total Total execution count of AI sub-agents
# TYPE agent_task_executions_total counter
agent_task_executions_total{agent_name="ScriptSupervisorAgent",status="success"} ${pipelineData ? '1' : '0'}
agent_task_executions_total{agent_name="VisualVFXAgent",status="success"} ${pipelineData ? '1' : '0'}
agent_task_executions_total{agent_name="AudioSoundtrackAgent",status="success"} ${pipelineData ? '1' : '0'}

# HELP genmedia_assets_generated_total Total media assets generated by type
genmedia_assets_generated_total{asset_type="storyboard"} ${pipelineData?.storyboards?.length || 0}
genmedia_assets_generated_total{asset_type="voice_table_read"} ${pipelineData?.audio_package?.voice_tracks?.length || 0}
genmedia_assets_generated_total{asset_type="audio_score"} ${pipelineData ? '1' : '0'}`}
        </pre>
      </div>
    </div>
  );
}
