import React, { useState } from 'react';
import { FileText, Copy, Check, FileCheck } from 'lucide-react';

export default function PostmortemView({ postmortemMarkdown }) {
  const [copied, setCopied] = useState(false);

  if (!postmortemMarkdown) {
    return null;
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(postmortemMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Basic custom markdown formatter
  const renderMarkdown = (text) => {
    if (!text) return null;
    const lines = text.split('\n');
    let insideCodeBlock = false;
    let codeContent = [];

    return lines.map((line, idx) => {
      // Handle Code Blocks
      if (line.trim().startsWith('```')) {
        if (insideCodeBlock) {
          insideCodeBlock = false;
          const renderedCode = (
            <pre key={`code-${idx}`} className="bg-slate-950/80 border border-white/5 rounded-none p-4 font-mono text-[10px] text-slate-300 my-3 overflow-x-auto leading-normal">
              <code>{codeContent.join('\n')}</code>
            </pre>
          );
          codeContent = [];
          return renderedCode;
        } else {
          insideCodeBlock = true;
          return null;
        }
      }

      if (insideCodeBlock) {
        codeContent.push(line);
        return null;
      }

      // Headers
      if (line.startsWith('# ')) {
        return <h1 key={idx} className="text-md font-bold text-white mb-3 mt-4 border-b border-white/5 pb-1 uppercase tracking-wide">{line.substring(2)}</h1>;
      }
      if (line.startsWith('## ')) {
        return <h2 key={idx} className="text-sm font-bold text-slate-200 mb-2 mt-4 flex items-center gap-1.5">{line.substring(3)}</h2>;
      }
      if (line.startsWith('### ')) {
        return <h3 key={idx} className="text-xs font-bold text-slate-300 mb-2 mt-3">{line.substring(4)}</h3>;
      }

      // Blockquotes / Alerts
      if (line.startsWith('> ')) {
        return (
          <blockquote key={idx} className="border-l-2 border-sky-400 bg-sky-400/5 p-3 rounded-none my-3 text-xs text-slate-300 italic leading-relaxed">
            {line.substring(2)}
          </blockquote>
        );
      }

      // List items
      if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
        return (
          <li key={idx} className="text-xs text-slate-400 ml-4 mb-1.5 list-disc leading-relaxed">
            {line.trim().substring(2)}
          </li>
        );
      }

      // Empty line
      if (line.trim() === '') {
        return <div key={idx} className="h-2"></div>;
      }

      // Default paragraph text with inline code parsing
      const parts = line.split(/(`[^`]+`)/g);
      const parsedLine = parts.map((part, pidx) => {
        if (part.startsWith('`') && part.endsWith('`')) {
          return <code key={pidx} className="bg-slate-900 text-sky-400 px-1.5 py-0.5 rounded-none text-[10px] font-mono border border-white/5">{part.slice(1, -1)}</code>;
        }
        return part;
      });

      return <p key={idx} className="text-xs text-slate-400 mb-2 leading-relaxed">{parsedLine}</p>;
    });
  };

  return (
    <div className="glass-card p-6 border border-white/5 bg-[#0a0b10] rounded-none">
      <div className="flex justify-between items-center mb-5">
        <div>
          <h2 className="text-sm uppercase tracking-wider font-extrabold text-gradient flex items-center gap-2">
            <FileText className="w-4 h-4 text-amber-500" /> SRE Incident Postmortem
          </h2>
          <p className="text-[10px] text-slate-500 uppercase tracking-widest font-mono mt-1">Official incident summary generated by Gemini</p>
        </div>

        <button 
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 text-[9px] font-mono font-bold bg-white/5 hover:bg-white/10 active:scale-98 border border-white/5 rounded-none transition"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span className="text-emerald-400">COPIED</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-slate-400" />
              <span>COPY REPORT</span>
            </>
          )}
        </button>
      </div>

      <div className="bg-slate-950/20 border border-white/5 rounded-none p-5 max-h-[500px] overflow-y-auto postmortem-container">
        {renderMarkdown(postmortemMarkdown)}
      </div>
    </div>
  );
}
