from prometheus_client import Counter, Histogram, Gauge, generate_latest, CONTENT_TYPE_LATEST
import time

# Prometheus Metrics Definitions for Grafana Observability

# 1. Agent Task Executions
AGENT_TASK_EXECUTIONS = Counter(
    'agent_task_executions_total',
    'Total execution count of AI sub-agents',
    ['agent_name', 'status']
)

# 2. Agent Execution Latency
AGENT_EXECUTION_LATENCY = Histogram(
    'agent_execution_duration_seconds',
    'Time spent in seconds by sub-agents completing tasks',
    ['agent_name', 'task_type'],
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0]
)

# 3. Gemini Token Consumption
GEMINI_TOKEN_USAGE = Counter(
    'gemini_token_count_total',
    'Total tokens consumed by Gemini models',
    ['model', 'token_type']  # input vs output
)

# 4. GenMedia Assets Created
GENMEDIA_ASSETS_CREATED = Counter(
    'genmedia_assets_generated_total',
    'Total media assets generated by type',
    ['asset_type']  # storyboard, audio_score, voice_table_read
)

# 5. Live Pipeline Status Gauge
PIPELINE_ACTIVE_GAUGE = Gauge(
    'cineflow_pipeline_active_tasks',
    'Number of active pre-production pipeline tasks currently processing'
)


class MetricsManager:
    @staticmethod
    def record_agent_task(agent_name: str, status: str = "success"):
        AGENT_TASK_EXECUTIONS.labels(agent_name=agent_name, status=status).inc()

    @staticmethod
    def record_token_usage(model: str, input_tokens: int, output_tokens: int):
        GEMINI_TOKEN_USAGE.labels(model=model, token_type="input").inc(input_tokens)
        GEMINI_TOKEN_USAGE.labels(model=model, token_type="output").inc(output_tokens)

    @staticmethod
    def record_asset_generated(asset_type: str, count: int = 1):
        GENMEDIA_ASSETS_CREATED.labels(asset_type=asset_type).inc(count)

    @staticmethod
    def get_prometheus_metrics() -> bytes:
        return generate_latest()

metrics_mgr = MetricsManager()
